# Generated by Django 3.1.6 on 2021-02-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uploader',
        ),
    ]
