# Generated by Django 3.1.6 on 2021-02-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210210_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='sno',
            field=models.AutoField(default=13, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
