# Generated by Django 3.1.6 on 2021-02-10 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20210210_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sno',
        ),
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
