# Generated by Django 3.1.6 on 2021-02-10 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20210210_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='time',
        ),
    ]
