# Generated by Django 3.1.6 on 2021-02-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_post_authormail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='authormail',
        ),
    ]
