# Generated by Django 3.1.6 on 2021-02-11 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0033_auto_20210211_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authormail',
            field=models.ManyToManyField(blank=True, related_name='authormail', to=settings.AUTH_USER_MODEL),
        ),
    ]
