# Generated by Django 3.1.6 on 2021-02-15 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_blogcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
