# Generated by Django 3.1.6 on 2021-02-16 09:23

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_post_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', multiselectfield.db.fields.MultiSelectField(choices=[('s_b', 'S.B'), ('g_b', 'G.B'), ('t_b', 'T.B.')], max_length=11)),
            ],
        ),
    ]
