# Generated by Django 3.1.6 on 2021-02-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_auto_20210216_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('General', 'General blog'), ('Study', 'Study blog'), ('Technical', 'Technical Blog')], max_length=32),
        ),
    ]
