# Generated by Django 2.2.12 on 2021-02-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0048_auto_20210217_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Generalblog', 'General blog'), ('Studyblog', 'Study blog'), ('Technicalblog', 'Technical Blog')], max_length=32),
        ),
    ]
