# Generated by Django 3.1.6 on 2021-02-11 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
